server:
  port: 8080
  servlet:
    context-path: /cms
spring:
  services:
    redis:
      image: redis:8.2.7-bookworm
      container_name: redis
      command: redis-server --requirepass "root"
      ports:
        - "6379:6379"
  application:
    name: SmashHub
  datasource:
    url: "jdbc:mysql://localhost:3306/badminton_shop"
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhlongbc28@gmail.com
    password: wrbfvamaaezllcgd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  otp:
    expiration-minutes: 5
    resend-cooldown-seconds: 60